name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar pytest
        run: pip install pytest

      - name: Ejecutar pruebas
        run: python -m pytest test_app.py


  build-and-deploy:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Build completado correctamente"

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/aws_key
          chmod 600 ~/.ssh/aws_key
          ssh-keyscan -H "${{ secrets.AWS_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy en AWS
        run: |
          ssh -i ~/.ssh/aws_key \
            "${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }}" \
            'cd ~/simulacro-despliegue && docker compose pull app-backend && docker compose up -d app-backend'

      - name: Verificar despliegue
        run: |
          echo "Despliegue completado correctamente"
